### ISSUE TITLE
Expand the spin projected magnetization used by vasp represented in Einstein summation convention.

### ISSUE THREAD

**Issue by hongyi-zhao** [wjxway/EasyEinsteinSummation#9]
I noticed the following spin projected magnetization used by vasp in its [PROCAR](https://www.vasp.at/wiki/index.php/PROCAR) file:

![image](https://user-images.githubusercontent.com/11155854/161782882-64bdd543-f21a-4d19-8652-d8b57bffda29.png)

If I understand correctly, the formula above is represented in Einstein summation convention. So I want to know if I can use `EasyEinsteinSummation` to expand and calculate the spin projected magnetization used by vasp represented in Einstein summation convention as shown above.

Regards,
HZ

**Comment by wjxway** [comment]
Sorry for the late reply. Unfortunately, I do not recommend using this package to do any formal computation right now because this package is no longer maintained and has a known bug. Please use [xAct package](http://www.xact.es/) instead, which has the same capability but more complete and reliable. Thanks!

**Comment by hongyi-zhao** [comment]
Thank you for your information. See [here](https://groups.google.com/g/xact/c/clwX4lqZxm0) for the relevant discussion.
